# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosite', '0006_task_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(help_text='Enter a description for the task.', max_length=300),
        ),
    ]
